window.PORTFOLIO = [
  {
    "id": "p0",
    "title": "Si Solamente",
    "category": "Film",
    "role": "Producer",
    "year": "2026",
    "image": "https://sofirichof.github.io/archive/netflix/assets/si-solamente/stills/SiSo_Still1.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/production/si-solamente-trailer.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/si-solamente.html",
    "description": "A SAG-AFTRA micro-budget narrative short. Five shoot days, eight locations, a ten-person cast, and a thirty-person crew. Best Picture, Redstone Film Festival 2026."
  },
  {
    "id": "p1",
    "title": "The Stories We Tell Ourselves",
    "category": "Film",
    "role": "Producer",
    "year": "2025",
    "image": "https://img.youtube.com/vi/Vp9FBdygTKM/hqdefault.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/production/stories-trailer.mp4",
    "youtube": "Vp9FBdygTKM",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/the-stories-we-tell-ourselves.html",
    "description": "Narrative Short · Drama · 15 min"
  },
  {
    "id": "p2",
    "title": "Pajuyuk Ancestral Knowledge",
    "category": "Film",
    "role": "Exec. Production Assistant",
    "year": "2025",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/pajuyuk.png",
    "video": "",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/pajuyuk-ancestral-knowledge.html",
    "description": "Documentary · 18 min"
  },
  {
    "id": "p3",
    "title": "Bird's Eye View",
    "category": "Film",
    "role": "Producer & Editor",
    "year": "2024",
    "image": "https://img.youtube.com/vi/ETdIUMwOOd0/hqdefault.jpg",
    "video": "",
    "youtube": "ETdIUMwOOd0",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/birds-eye-view.html",
    "description": "Drama Short · 5 min"
  },
  {
    "id": "p4",
    "title": "Alike Loves",
    "category": "Film",
    "role": "Solo Project",
    "year": "2024",
    "image": "https://img.youtube.com/vi/MQlT_NU6HVQ/hqdefault.jpg",
    "video": "",
    "youtube": "MQlT_NU6HVQ",
    "detail": "",
    "description": "Rom-Com Short · 3 min"
  },
  {
    "id": "p5",
    "title": "Lucky Streak",
    "category": "Film",
    "role": "Director & Editor",
    "year": "2024",
    "image": "https://img.youtube.com/vi/kFhCE3E2zDY/hqdefault.jpg",
    "video": "",
    "youtube": "kFhCE3E2zDY",
    "detail": "",
    "description": "Narrative Documentary · 5 min"
  },
  {
    "id": "p6",
    "title": "Till Death Do Us Part",
    "category": "Film",
    "role": "Producer & Editor",
    "year": "2025",
    "image": "https://img.youtube.com/vi/kH-951HUFS0/hqdefault.jpg",
    "video": "",
    "youtube": "kH-951HUFS0",
    "detail": "",
    "description": "Comedy Short · 5 min"
  },
  {
    "id": "p7",
    "title": "Cine Final",
    "category": "Film",
    "role": "Director & DP",
    "year": "2025",
    "image": "https://img.youtube.com/vi/thmD8H7qK24/hqdefault.jpg",
    "video": "",
    "youtube": "thmD8H7qK24",
    "detail": "",
    "description": "Cinematography Exercise"
  },
  {
    "id": "p8",
    "title": "The In Between",
    "category": "Film",
    "role": "1st AD",
    "year": "2024",
    "image": "https://img.youtube.com/vi/7aJZ3AvY3IU/hqdefault.jpg",
    "video": "",
    "youtube": "7aJZ3AvY3IU",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/the-in-between.html",
    "description": "Music Video · 8 min"
  },
  {
    "id": "p9",
    "title": "By Design",
    "category": "Film",
    "role": "1st Assistant Director",
    "year": "2024",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/ByDesign.png",
    "video": "",
    "youtube": "",
    "detail": "",
    "description": "Narrative Short"
  },
  {
    "id": "p10",
    "title": "El Futuro para Mama y Yo",
    "category": "Film",
    "role": "1st Assistant Director",
    "year": "2024",
    "image": "",
    "video": "",
    "youtube": "",
    "detail": "",
    "description": "Narrative Short · Spanish-language"
  },
  {
    "id": "p11",
    "title": "Vestido para Mama",
    "category": "Film",
    "role": "Script Supervisor",
    "year": "2024",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/Vestidoparamama.png",
    "video": "",
    "youtube": "",
    "detail": "",
    "description": "Narrative Short"
  },
  {
    "id": "p12",
    "title": "Growing Pains",
    "category": "Film",
    "role": "Script Supervisor",
    "year": "2024",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/GrowingPains.png",
    "video": "",
    "youtube": "",
    "detail": "",
    "description": "Narrative Short"
  },
  {
    "id": "p13",
    "title": "Chameleon",
    "category": "Film",
    "role": "Script Supervisor",
    "year": "2024",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/chameleon.png",
    "video": "",
    "youtube": "",
    "detail": "https://vimeo.com/1016565914?share=copy",
    "description": "Narrative Short"
  },
  {
    "id": "p14",
    "title": "Aftershock",
    "category": "Film",
    "role": "2nd AC",
    "year": "2024",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/Aftershock.png",
    "video": "",
    "youtube": "",
    "detail": "",
    "description": "Narrative Short"
  },
  {
    "id": "p15",
    "title": "Acceso Total",
    "broadcaster": "Telemundo 52",
    "category": "Television",
    "role": "Interviewer",
    "year": "2026",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/acesso-total-hollywood-premiere.png",
    "video": "",
    "youtube": "b4WxJcoeT0c",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/acceso-total-telemundo-52.html",
    "description": "Broadcast · Entertainment"
  },
  {
    "id": "p16",
    "title": "Acceso Total - Independence Days",
    "broadcaster": "Telemundo 52",
    "category": "Television",
    "role": "Segment Producer",
    "year": "2025",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/acesso-total-independence-days.png",
    "video": "",
    "youtube": "kVxZsvJysHA",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/acceso-total-telemundo-52.html",
    "description": "Broadcast · Cultural Segment"
  },
  {
    "id": "p17",
    "title": "Live With TY",
    "category": "Television",
    "role": "Chief Editor",
    "year": "2024",
    "image": "https://sofirichof.github.io/archive/netflix/assets/live-with-ty/logo.png",
    "video": "",
    "youtube": "g2gvMf2UDbQ",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/live-with-ty-s1-ep11.html",
    "description": "Broadcast · Sports · NATAS Award"
  },
  {
    "id": "p18",
    "title": "Zona de Estrellas",
    "category": "Television",
    "role": "Production Assistant",
    "year": "2024",
    "image": "https://img.youtube.com/vi/rz87SYmnLt4/hqdefault.jpg",
    "video": "",
    "youtube": "rz87SYmnLt4",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/zona-latina-chile.html",
    "description": "Live Variety · Santiago, Chile"
  },
  {
    "id": "p19",
    "title": "Sabores",
    "category": "Television",
    "role": "Production Assistant",
    "year": "2024",
    "image": "https://sofirichof.github.io/archive/netflix/assets/thumbs/sabores.png",
    "video": "",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/zona-latina-chile.html",
    "description": "Live Variety · Santiago, Chile"
  },
  {
    "id": "p20",
    "title": "Bay State",
    "category": "Television",
    "role": "Producer",
    "year": "2024-2026",
    "image": "https://img.youtube.com/vi/pLEuklMB0Xc/hqdefault.jpg",
    "video": "",
    "youtube": "pLEuklMB0Xc",
    "detail": "https://sofirichof.github.io/archive/netflix/projects/baystate-season-48-50.html",
    "description": "TV Drama · Multi-camera"
  },
  {
    "id": "p21",
    "title": "The Loft — Comedy",
    "category": "Advertising",
    "role": "Laundry Loft · Adathon",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/laundry-loft-comedy.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/laundry-loft-comedy.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Comedy spot for Laundry Loft, a Williamsburg laundromat pitched as the neighborhood's third space. As the team's AI maker, I generated every shot in Higgsfield Cinema Studio from prompts I wrote shot by shot."
  },
  {
    "id": "p22",
    "title": "AI Concept Ad",
    "category": "Advertising",
    "role": "MilkPEP · AI-Generated Spot",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/milkpep-ai-ad.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/milkpep-ai-ad.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A fully AI-generated ad for the MilkPEP pitch — I generated the footage in Studio S, the prompt tool I built, then cut it into a finished spot."
  },
  {
    "id": "p23",
    "title": "Full Campaign Reel",
    "category": "Advertising",
    "role": "MilkPEP · New Business Pitch",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/milkpep-reel.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/milkpep-reel.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "New-business sizzle reel edited for the MilkPEP pitch — a fast-moving showcase of Supergood's campaign work, assembled to win the room."
  },
  {
    "id": "p24",
    "title": "Run the Numbers",
    "category": "Advertising",
    "role": "US Bank · Super Bowl Ideation",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/usbank-run-the-numbers.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/usbank-run-the-numbers.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "AI-generated ideation for US Bank — a concept for a potential Super Bowl activation where a live podcast runs during the game's non-play time."
  },
  {
    "id": "p25",
    "title": "Real MVP — Izzy",
    "category": "Advertising",
    "role": "US Bank × NFL · Real MVP",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/realmvp-izzy.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/realmvp-izzy.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Athlete profile edit from the Real MVP series — flag-football standout Izzy Gerace — featuring a custom autograph write-on animation."
  },
  {
    "id": "p26",
    "title": "Real MVP — Mendoza",
    "category": "Advertising",
    "role": "US Bank × NFL · Real MVP",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/realmvp-mendoza.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/realmvp-mendoza.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Athlete profile cutdown from the Real MVP series — quarterback Fernando Mendoza — tightened to a 13-second social edit."
  },
  {
    "id": "p27",
    "title": "Power of Us — BTS",
    "category": "Advertising",
    "role": "US Bank × NFL · Social",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/usbank-nfl-bts.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/usbank-nfl-bts.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Behind-the-scenes hype cut for US Bank's NFL \"Power of Us\" campaign, built for 9:16 social with a soundbite-driven edit."
  },
  {
    "id": "p28",
    "title": "PSA — Move Your Money",
    "category": "Advertising",
    "role": "US Bank · Social",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/usbank-nfl-psa.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/usbank-nfl-psa.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Client-approved PSA social spot with supers and disclosure finessing handled for compliance."
  },
  {
    "id": "p29",
    "title": "Business Banking",
    "category": "Advertising",
    "role": "US Bank × NFL · Social",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/usbank-nfl-business-banking.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/usbank-nfl-business-banking.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Social spot pairing US Bank's business banking message with NFL talent, delivered with the updated league lockup."
  },
  {
    "id": "p30",
    "title": "Bloopers",
    "category": "Advertising",
    "role": "US Bank × NFL · Social",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/usbank-nfl-bloopers.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/usbank-nfl-bloopers.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A lighter social cut from the US Bank × NFL shoot — outtakes edited for scroll-native rhythm."
  },
  {
    "id": "p31",
    "title": "Affirmation Cake",
    "category": "Advertising",
    "role": "Capital One · Always One Step Ahead",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/AFFIRMATIONCAKE-THUMB.png",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/capital-one/affirmation-cake.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "One of four edutainment-style vertical videos built for TikTok and Instagram."
  },
  {
    "id": "p32",
    "title": "Ice Bath",
    "category": "Advertising",
    "role": "Capital One · Always One Step Ahead",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/ICEBATH-THUMB.png",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/capital-one/ice-bath.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Social-first financial confidence concept using fast visual payoff and scroll-native pacing."
  },
  {
    "id": "p33",
    "title": "Vision Board",
    "category": "Advertising",
    "role": "Capital One · Always One Step Ahead",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/VISIONBOARD-THUMB.png",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/capital-one/vision-board.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A short-form concept connecting planning, optimism, and being financially prepared."
  },
  {
    "id": "p34",
    "title": "Yoga",
    "category": "Advertising",
    "role": "Capital One · Always One Step Ahead",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/YOGA-THUMB.png",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/capital-one/yoga.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Edutainment deliverable designed for quick comprehension and platform-native humor."
  },
  {
    "id": "p35",
    "title": "Safe Roads",
    "category": "Advertising",
    "role": "MassDOT · Smart Choices, Safe Roads",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/MASSDOT_THUMB.png",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/mass-dot.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Cable-ready road-safety ad concept designed as a concise under-60-second public message."
  },
  {
    "id": "p36",
    "title": "Social Ad",
    "category": "Advertising",
    "role": "Affordable Art Fair · AdLab",
    "year": "",
    "image": "",
    "video": "",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "15-30 second 4:5 social ad for Instagram and Facebook."
  },
  {
    "id": "p37",
    "title": "Only Humans Can",
    "category": "Advertising",
    "role": "SAG-AFTRA Anti-AI Campaign Mockup · 2025",
    "year": "",
    "image": "https://img.youtube.com/vi/aqJrNGxHNVY/hqdefault.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/spec/only-humans-can.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Single idea: To act is to be human. Slogan: Only Humans Can."
  },
  {
    "id": "p38",
    "title": "Joe Is Your Man",
    "category": "Advertising",
    "role": "Trader Joe's Campaign Mockup · 2025",
    "year": "",
    "image": "https://img.youtube.com/vi/lKSkqYtx9zw/hqdefault.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/spec/joe-is-your-man.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Single idea: We make adulting easy. Slogan: Joe is your man."
  },
  {
    "id": "p39",
    "title": "Ranch Practice",
    "category": "Advertising",
    "role": "Spec · Solo Exercise",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/RANCHSPEC_THUMB.png",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/ranch-spec.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "Solo spec exercise — short-form product concept exploring lifestyle framing and visual pacing."
  },
  {
    "id": "p40",
    "title": "Motion Test 01",
    "category": "Advertising",
    "role": "Soul Cinema × Kling · AI R&D",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/soul/c2.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/soul/c2.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A photoreal still generated in Higgsfield Soul Cinema, animated to motion with Kling."
  },
  {
    "id": "p41",
    "title": "Motion Test 02",
    "category": "Advertising",
    "role": "Soul Cinema × Kling · AI R&D",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/soul/c3.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/soul/c3.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A photoreal still generated in Higgsfield Soul Cinema, animated to motion with Kling."
  },
  {
    "id": "p42",
    "title": "Motion Test 03",
    "category": "Advertising",
    "role": "Soul Cinema × Kling · AI R&D",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/supergood/soul/c4.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/supergood/soul/c4.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A photoreal still generated in Higgsfield Soul Cinema, animated to motion with Kling."
  },
  {
    "id": "p43",
    "title": "Merit Fragrance Spec Ad",
    "category": "Advertising",
    "role": "Merit · Spec Social Motion",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/spec/merit-fragrance.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/spec/merit-fragrance.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A soft atmospheric spec ad built around the perfume bottle and fragrance notes as visual world-building."
  },
  {
    "id": "p44",
    "title": "Bluebird Hard Water Spec Ad",
    "category": "Advertising",
    "role": "Bluebird Hard Water · Spec Social Motion",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/spec/bluebird-hard-water.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/spec/bluebird-hard-water.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A short-form spec ad built around product mood, brand texture, and scroll-stopping visual atmosphere."
  },
  {
    "id": "p45",
    "title": "Bloom Creatine Spec Ad",
    "category": "Advertising",
    "role": "Bloom · Spec Social Motion",
    "year": "",
    "image": "https://sofirichof.github.io/archive/netflix/assets/ad/spec/bloom-creatine.jpg",
    "video": "https://sofirichof.github.io/archive/netflix/media/ad/spec/bloom-creatine.mp4",
    "youtube": "",
    "detail": "https://sofirichof.github.io/archive/netflix/agency.html",
    "description": "A vertical spec ad built around wellness, product texture, and high-energy social-first motion."
  }
];
